"""Runtime configuration, loaded from environment / .env."""
from __future__ import annotations

import os
from dataclasses import dataclass, field

from dotenv import load_dotenv

load_dotenv()


def _bool(name: str, default: bool = False) -> bool:
    return os.getenv(name, str(default)).strip().lower() in {"1", "true", "yes", "on"}


def _int(name: str, default: int) -> int:
    try:
        return int(os.getenv(name, "").strip() or default)
    except ValueError:
        return default


def _ids(name: str) -> set[int]:
    raw = os.getenv(name, "").strip()
    if not raw:
        return set()
    out: set[int] = set()
    for part in raw.split(","):
        part = part.strip()
        if part:
            out.add(int(part))
    return out


@dataclass(frozen=True)
class Branding:
    name: str = os.getenv("COMPANY_NAME", "Your Company")
    tagline: str = os.getenv("COMPANY_TAGLINE", "Payment Confirmation")
    website: str = os.getenv("COMPANY_WEBSITE", "")
    support: str = os.getenv("COMPANY_SUPPORT", "")
    primary: str = os.getenv("BRAND_PRIMARY", "#5B6BF0")
    accent: str = os.getenv("BRAND_ACCENT", "#3ED598")
    logo_path: str = os.getenv("COMPANY_LOGO", "assets/logo.png")
    footer_note: str = os.getenv(
        "FOOTER_NOTE",
        "This transaction is generated by the system. Please verify your bank "
        "statement with the reference number, transaction number, or UTR number.",
    )


@dataclass(frozen=True)
class Config:
    telegram_token: str = os.getenv("TELEGRAM_BOT_TOKEN", "")
    allowed_chat_ids: set[int] = field(default_factory=lambda: _ids("ALLOWED_CHAT_IDS"))
    openai_api_key: str = os.getenv("OPENAI_API_KEY", "")
    extraction_model: str = os.getenv("EXTRACTION_MODEL", "gpt-4o-mini")
    max_concurrency: int = _int("MAX_CONCURRENCY", 5)
    default_transfer_mode: str = os.getenv("DEFAULT_TRANSFER_MODE", "IMPS")
    branding: Branding = field(default_factory=Branding)

    def validate(self) -> None:
        missing = []
        if not self.telegram_token:
            missing.append("TELEGRAM_BOT_TOKEN")
        if not self.openai_api_key:
            missing.append("OPENAI_API_KEY")
        if missing:
            raise SystemExit(f"Missing required env vars: {', '.join(missing)}")


CONFIG = Config()
