"""Runtime configuration, loaded from environment / .env."""
from __future__ import annotations

import os
from dataclasses import dataclass, field

from dotenv import load_dotenv

load_dotenv()


def _bool(name: str, default: bool = False) -> bool:
    return os.getenv(name, str(default)).strip().lower() in {"1", "true", "yes", "on"}


def _codes(name: str) -> set[str]:
    return {p.strip().upper() for p in os.getenv(name, "").replace(";", ",").split(",") if p.strip()}


def _int(name: str, default: int) -> int:
    try:
        return int(os.getenv(name, "").strip() or default)
    except ValueError:
        return default


def _ids(name: str) -> set[int]:
    raw = os.getenv(name, "").strip()
    if not raw:
        return set()
    out: set[int] = set()
    for part in raw.split(","):
        part = part.strip()
        if part:
            out.add(int(part))
    return out


@dataclass(frozen=True)
class Branding:
    name: str = os.getenv("COMPANY_NAME", "Your Company")
    tagline: str = os.getenv("COMPANY_TAGLINE", "Payment Confirmation")
    website: str = os.getenv("COMPANY_WEBSITE", "")
    support: str = os.getenv("COMPANY_SUPPORT", "")
    primary: str = os.getenv("BRAND_PRIMARY", "#5B6BF0")
    accent: str = os.getenv("BRAND_ACCENT", "#3ED598")
    logo_path: str = os.getenv("COMPANY_LOGO", "assets/logo.png")
    footer_note: str = os.getenv(
        "FOOTER_NOTE",
        "This transaction is generated by the system. Please verify your bank "
        "statement with the reference number, transaction number, or UTR number.",
    )


@dataclass(frozen=True)
class Config:
    telegram_token: str = os.getenv("TELEGRAM_BOT_TOKEN", "")
    allowed_chat_ids: set[int] = field(default_factory=lambda: _ids("ALLOWED_CHAT_IDS"))

    # openai | gemini | auto  (auto = OpenAI until its credit runs out, then Gemini)
    provider: str = os.getenv("PROVIDER", "openai").strip().lower()
    openai_api_key: str = os.getenv("OPENAI_API_KEY", "")
    extraction_model: str = os.getenv("EXTRACTION_MODEL", "gpt-4o-mini")
    gemini_api_key: str = os.getenv("GEMINI_API_KEY", "")
    gemini_model: str = os.getenv("GEMINI_MODEL", "gemini-3.5-flash-lite")

    max_concurrency: int = _int("MAX_CONCURRENCY", 5)
    default_transfer_mode: str = os.getenv("DEFAULT_TRANSFER_MODE", "IMPS")
    branding: Branding = field(default_factory=Branding)

    # Also send the recreated slip to this channel when the caption carries one
    # of ROUTE_CODES. 0 = feature off.
    slip_feed_channel: int = _int("SLIP_FEED_CHANNEL", 0)
    route_codes: set[str] = field(default_factory=lambda: _codes("ROUTE_CODES"))

    def validate(self) -> None:
        missing = []
        if not self.telegram_token:
            missing.append("TELEGRAM_BOT_TOKEN")
        if self.provider in ("openai", "auto") and not self.openai_api_key:
            missing.append("OPENAI_API_KEY")
        if self.provider in ("gemini", "auto") and not self.gemini_api_key:
            # auto can run on OpenAI alone; it just can't fail over
            if self.provider == "gemini":
                missing.append("GEMINI_API_KEY")
        if self.provider not in ("openai", "gemini", "auto"):
            raise SystemExit(f"PROVIDER must be openai, gemini or auto (got {self.provider!r})")
        if missing:
            raise SystemExit(f"Missing required env vars: {', '.join(missing)}")


CONFIG = Config()
